# -*- coding: utf-8 -*-
"""Input from user.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13hONd33GpQUsYIZuBPg4oPa7RidYOXbI
"""

import streamlit as st

title = st.text_input('Movie title', 'Life of Brian')
st.write('The current movie title is', title)